[package]
name = "xilang"
version = "0.1.0"
authors = ["XiPotatonium <xipotatonium@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

clap = "~2.33"
lalrpop-util = "0.19.4"
regex = "1"
lazy_static = "1.4.0"

[build-dependencies]
lalrpop = "0.19.4"

[[bin]]
name = "xilang"
path = "src/xilang.rs"

[[bin]]
name = "xivm"
path = "src/xivm.rs"

